#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.0.280225.1+7cd366a738
//       
//       Command:
//           LottieGen -Language Cppwinrt -Namespace CppWinUIGallery -WinUIVersion 3.0 -InputFile Test.json
//       
//       Input file:
//           Test.json (52737 bytes created 15:04+03:00 Aug 7 2024)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Test.g.h"

namespace winrt::CppWinUIGallery
{
    // Name:        Comp 1
    // Frame rate:  100 fps
    // Frame count: 300
    // Duration:    3000.0 mS
    // ____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |  mS   |   Progress   |
    // |____________________________|______________________________|_______|_______|______________|
    // | NormalToPointerOver_Start  | M_NormalToPointerOver_Start  |     0 |   0.0 | 0.0F         |
    // | NormalToPointerOver_End    | M_NormalToPointerOver_End    |     9 |  90.0 | 0.030166667F |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |    30 | 300.0 | 0.100166664F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    39 | 390.0 | 0.130166665F |
    // --------------------------------------------------------------------------------------------
    namespace implementation
    {
        class Test
            : public TestT<Test>
        {
            const int c_loadedImageSurfaceCount = 3;
            int m_loadCompletedEventCount{};
            bool m_isImageLoadingAsynchronous{};
            bool m_isImageLoadingCompleted{};
            bool m_isImageLoadingStarted{};
            bool m_isTryCreateAnimatedVisualCalled{};
            winrt::event<Windows::Foundation::TypedEventHandler<
                Microsoft::UI::Xaml::Controls::IDynamicAnimatedVisualSource,
                Windows::Foundation::IInspectable>> m_IDynamicAnimatedVisualSourceEvent{};
            winrt::event<Microsoft::UI::Xaml::Data::PropertyChangedEventHandler> m_PropertyChanged{};
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_0{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_1{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_2{ nullptr };
            void EnsureImageLoadingStarted();
            void HandleLoadCompleted(
                winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface sender,
                winrt::Microsoft::UI::Xaml::Media::LoadedImageSourceLoadCompletedEventArgs e);
        public:
            // Animation duration: 3.000 seconds.
            static constexpr int64_t c_durationTicks{ 30000000L };

            // Marker: NormalToPointerOver_Start.
            static constexpr float M_NormalToPointerOver_Start{ 0.0F };

            // Marker: NormalToPointerOver_End.
            static constexpr float M_NormalToPointerOver_End{ 0.030166667F };

            // Marker: PointerOverToPressed_Start.
            static constexpr float M_PointerOverToPressed_Start{ 0.100166664F };

            // Marker: PointerOverToPressed_End.
            static constexpr float M_PointerOverToPressed_End{ 0.130166665F };

            winrt::event_token PropertyChanged(winrt::Microsoft::UI::Xaml::Data::PropertyChangedEventHandler const& handler);
            void PropertyChanged(winrt::event_token const& token) noexcept;

            winrt::event_token AnimatedVisualInvalidated(
                winrt::Windows::Foundation::TypedEventHandler<Microsoft::UI::Xaml::Controls::IDynamicAnimatedVisualSource, IInspectable> const& handler);
            void AnimatedVisualInvalidated(winrt::event_token const& token) noexcept;

            /// <summary>
            /// If this property is set to true, <see cref="TryCreateAnimatedVisual"/> will return
            /// null until all images have loaded. When all images have loaded,
            /// <see cref="TryCreateAnimatedVisual"/> will return the AnimatedVisual. Once
            /// <see cref="TryCreateAnimatedVisual"/> is called, changes made to this property will
            /// be ignored. Default value is false.
            /// </summary>
            bool IsImageLoadingAsynchronous();
            void IsImageLoadingAsynchronous(bool value);

            /// <summary>
            /// Returns true if all images have finished loading.
            /// </summary>
            bool IsImageLoadingCompleted();

            winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
                winrt::Microsoft::UI::Composition::Compositor const& compositor);

            winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
                winrt::Microsoft::UI::Composition::Compositor const& compositor,
                winrt::Windows::Foundation::IInspectable& diagnostics);

            // Gets the number of frames in the animation.
            double FrameCount();

            // Gets the framerate of the animation.
            double Framerate();

            // Gets the duration of the animation.
            winrt::Windows::Foundation::TimeSpan Duration();

            // Converts a zero-based frame number to the corresponding progress value denoting the
            // start of the frame.
            double FrameToProgress(double frameNumber);

            // Returns a map from marker names to corresponding progress values.
            winrt::Windows::Foundation::Collections::IMapView<hstring, double> Markers();

            // Sets the color property with the given name, or does nothing if no such property
            // exists.
            void SetColorProperty(hstring const& propertyName, winrt::Windows::UI::Color value);

            // Sets the scalar property with the given name, or does nothing if no such property
            // exists.
            void SetScalarProperty(hstring const& propertyName, double value);
        };
    }

    namespace factory_implementation
    {
        struct Test : TestT<Test, implementation::Test>
        {
        };
    }
}
